url: http://tomsturge.co
ver: 3.1.5
title: Tom Sturge - Front-end Architect, UX Designer and Educator
desc: Making beautiful responsive and semantic user experiences for over 10 years. Working with individuals, small businesses and large international teams to create a wide variety of internet products. Specialising in front-end development, utilising modern JS technologies and agile workflows.


markdown: rdiscount
permalink: /:categories/:title
paginate: 10
exclude: [sass, CNAME]

collections:
- portfolio
gems:
  - jekyll-sitemap
